"use server";
/*
  THIS FUNCTION DECREMENTS THE AVAILABLE UNITS OF PRODUCTS
  AFTER A SUCCESSFULL ORDER. IF ORDER IS CANCELLED, THE ORDERED
  UNITS ARE ADDED BACK TO AVAILABLE UNIT PROPERTY OF EACH PRODUCT
*/
export default async function UpdateAvailableProducts(productIds){

}