import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { resolve } from "styled-jsx/css";
import { CartProvider } from "@/contexts/CartProvider";
import AUTH_SESSION_PROVIDER from "@/contexts/NextAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  interactiveWidget: 'resizes-content',
};


export default async function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, interactive-widget=resizes-content" />
      </head>
      <body className="antialiased">
        <AUTH_SESSION_PROVIDER>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <CartProvider>
              <main>{children}</main>
            </CartProvider>
          </ThemeProvider>
        </AUTH_SESSION_PROVIDER>
      </body>
    </html>
  )
}